### ISSUE TITLE
npm 无法下载 提示未注册

### ISSUE THREAD

**Issue by H402861965** [AMap-Web/amap-screeshot#1]
npm ERR! code E404
npm ERR! 404 Not found : '
npm ERR! 404
npm ERR! 404  ''' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain special characters ("~'!()*")
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by yangyanggu** [comment]
这个是你npm安装的包名不合理
